export type MarketingLocale = {
  code: string;
  label: string;
  dir?: "rtl";
  headline: string;
  subhead: string;
  learn: string;
  markets: string;
  practice: string;
  risk: string;
  cta: string;
  disclaimer: string;
  countries: string[];
};

export const marketingLocales: Record<string, MarketingLocale> = {
  en:{code:"en",label:"English",headline:"Understand global markets in your language.",subhead:"NexAI brings financial education, market intelligence and safe trading practice into one Africa-built platform.",learn:"Learn financial markets step by step",markets:"Track global markets with clear data labels",practice:"Practise with paper trading before risking capital",risk:"Use built-in risk checks and learning tools",cta:"Explore NexAI Global Markets",disclaimer:"Education and simulation only. Real-money execution is not enabled.",countries:["South Africa","Nigeria","Kenya","Ghana","United Kingdom","United States","Canada","Australia","Singapore"]},
  es:{code:"es",label:"Español",headline:"Entiende los mercados globales en tu idioma.",subhead:"NexAI reúne educación financiera, inteligencia de mercados y práctica segura de trading en una plataforma creada en África.",learn:"Aprende los mercados financieros paso a paso",markets:"Sigue los mercados globales con datos claramente identificados",practice:"Practica con trading simulado antes de arriesgar capital",risk:"Utiliza controles de riesgo y herramientas de aprendizaje",cta:"Explora NexAI Global Markets",disclaimer:"Solo educación y simulación. La ejecución con dinero real no está habilitada.",countries:["México","España","Colombia","Argentina","Chile","Perú"]},
  pt:{code:"pt",label:"Português",headline:"Entenda os mercados globais no seu idioma.",subhead:"A NexAI reúne educação financeira, inteligência de mercado e prática segura de negociação numa plataforma criada em África.",learn:"Aprenda os mercados financeiros passo a passo",markets:"Acompanhe mercados globais com dados claramente identificados",practice:"Pratique com negociação simulada antes de arriscar capital",risk:"Use controlos de risco e ferramentas de aprendizagem",cta:"Explore a NexAI Global Markets",disclaimer:"Apenas educação e simulação. A execução com dinheiro real não está ativada.",countries:["Brasil","Portugal","Angola","Moçambique"]},
  fr:{code:"fr",label:"Français",headline:"Comprenez les marchés mondiaux dans votre langue.",subhead:"NexAI réunit éducation financière, intelligence de marché et entraînement au trading dans une plateforme conçue en Afrique.",learn:"Apprenez les marchés financiers étape par étape",markets:"Suivez les marchés mondiaux avec des données clairement identifiées",practice:"Entraînez-vous avec le trading simulé avant de risquer du capital",risk:"Utilisez des contrôles de risque et des outils d’apprentissage",cta:"Découvrir NexAI Global Markets",disclaimer:"Éducation et simulation uniquement. L’exécution avec de l’argent réel n’est pas activée.",countries:["France","Canada","Côte d’Ivoire","Sénégal","Cameroun","RDC"]},
  ar:{code:"ar",label:"العربية",dir:"rtl",headline:"افهم الأسواق العالمية بلغتك.",subhead:"تجمع NexAI بين التعليم المالي وذكاء الأسواق والتدريب الآمن على التداول في منصة مبنية في أفريقيا.",learn:"تعلّم الأسواق المالية خطوة بخطوة",markets:"تابع الأسواق العالمية مع توضيح حالة البيانات",practice:"تدرّب بالتداول الافتراضي قبل المخاطرة برأس المال",risk:"استخدم أدوات إدارة المخاطر والتعلّم",cta:"اكتشف NexAI Global Markets",disclaimer:"للتعليم والمحاكاة فقط. التداول بأموال حقيقية غير مفعّل.",countries:["الإمارات","السعودية","مصر","المغرب","الأردن"]},
  hi:{code:"hi",label:"हिन्दी",headline:"वैश्विक बाज़ारों को अपनी भाषा में समझें।",subhead:"NexAI वित्तीय शिक्षा, बाज़ार इंटेलिजेंस और सुरक्षित ट्रेडिंग अभ्यास को अफ्रीका में निर्मित एक प्लेटफ़ॉर्म पर लाता है।",learn:"वित्तीय बाज़ारों को चरण-दर-चरण सीखें",markets:"स्पष्ट डेटा लेबल के साथ वैश्विक बाज़ार देखें",practice:"पूंजी जोखिम में डालने से पहले पेपर ट्रेडिंग करें",risk:"जोखिम जांच और सीखने के टूल उपयोग करें",cta:"NexAI Global Markets देखें",disclaimer:"केवल शिक्षा और सिमुलेशन। वास्तविक धन से ट्रेडिंग सक्षम नहीं है।",countries:["भारत"]},
  "zh-CN":{code:"zh-CN",label:"中文",headline:"用你的语言理解全球市场。",subhead:"NexAI 将金融教育、市场洞察和安全的模拟交易练习整合在一个非洲打造的平台中。",learn:"循序渐进学习金融市场",markets:"通过清晰标注的数据追踪全球市场",practice:"在投入真实资金前先进行模拟交易",risk:"使用风险检查与学习工具",cta:"探索 NexAI Global Markets",disclaimer:"仅用于教育和模拟。尚未启用真实资金交易。",countries:["新加坡","马来西亚","香港"]},
  bn:{code:"bn",label:"বাংলা",headline:"আপনার ভাষায় বিশ্ববাজার বুঝুন।",subhead:"NexAI আর্থিক শিক্ষা, বাজার বিশ্লেষণ এবং নিরাপদ ট্রেডিং অনুশীলনকে আফ্রিকায় তৈরি একটি প্ল্যাটফর্মে একত্রিত করে।",learn:"ধাপে ধাপে আর্থিক বাজার শিখুন",markets:"স্পষ্ট ডেটা লেবেলসহ বিশ্ববাজার অনুসরণ করুন",practice:"মূলধন ঝুঁকিতে ফেলার আগে পেপার ট্রেডিং অনুশীলন করুন",risk:"ঝুঁকি পরীক্ষা ও শেখার টুল ব্যবহার করুন",cta:"NexAI Global Markets দেখুন",disclaimer:"শুধু শিক্ষা ও সিমুলেশন। বাস্তব অর্থে ট্রেডিং চালু নয়।",countries:["বাংলাদেশ","ভারত"]},
  ur:{code:"ur",label:"اردو",dir:"rtl",headline:"عالمی منڈیوں کو اپنی زبان میں سمجھیں۔",subhead:"NexAI مالی تعلیم، مارکیٹ انٹیلیجنس اور محفوظ ٹریڈنگ پریکٹس کو افریقہ میں بنائے گئے ایک پلیٹ فارم پر یکجا کرتا ہے۔",learn:"مالی منڈیوں کو مرحلہ وار سیکھیں",markets:"واضح ڈیٹا لیبل کے ساتھ عالمی منڈیوں کو دیکھیں",practice:"سرمایہ خطرے میں ڈالنے سے پہلے پیپر ٹریڈنگ کریں",risk:"رسک چیک اور تعلیمی ٹولز استعمال کریں",cta:"NexAI Global Markets دریافت کریں",disclaimer:"صرف تعلیم اور سمیولیشن۔ حقیقی رقم سے ٹریڈنگ فعال نہیں ہے۔",countries:["پاکستان","بھارت"]},
  id:{code:"id",label:"Bahasa Indonesia",headline:"Pahami pasar global dalam bahasa Anda.",subhead:"NexAI menyatukan edukasi keuangan, intelijen pasar, dan latihan trading yang aman dalam satu platform buatan Afrika.",learn:"Pelajari pasar keuangan langkah demi langkah",markets:"Pantau pasar global dengan label data yang jelas",practice:"Berlatih paper trading sebelum mempertaruhkan modal",risk:"Gunakan pemeriksaan risiko dan alat pembelajaran",cta:"Jelajahi NexAI Global Markets",disclaimer:"Hanya untuk edukasi dan simulasi. Eksekusi dengan uang nyata belum diaktifkan.",countries:["Indonesia"]},
  de:{code:"de",label:"Deutsch",headline:"Verstehe globale Märkte in deiner Sprache.",subhead:"NexAI verbindet Finanzbildung, Marktintelligenz und sicheres Trading-Training auf einer in Afrika entwickelten Plattform.",learn:"Finanzmärkte Schritt für Schritt lernen",markets:"Globale Märkte mit klar gekennzeichneten Daten verfolgen",practice:"Mit Paper Trading üben, bevor Kapital riskiert wird",risk:"Risikochecks und Lernwerkzeuge nutzen",cta:"NexAI Global Markets entdecken",disclaimer:"Nur Bildung und Simulation. Echtgeld-Ausführung ist nicht aktiviert.",countries:["Deutschland","Österreich","Schweiz"]},
  ja:{code:"ja",label:"日本語",headline:"世界の市場を、あなたの言語で理解する。",subhead:"NexAI は金融教育、市場インテリジェンス、安全なトレード練習をアフリカ発の一つのプラットフォームに統合します。",learn:"金融市場を段階的に学ぶ",markets:"明確なデータ表示で世界市場を追跡",practice:"資金をリスクにさらす前にペーパートレードで練習",risk:"リスクチェックと学習ツールを活用",cta:"NexAI Global Markets を見る",disclaimer:"教育とシミュレーションのみ。実資金での取引は有効化されていません。",countries:["日本"]},
  ko:{code:"ko",label:"한국어",headline:"글로벌 시장을 당신의 언어로 이해하세요.",subhead:"NexAI는 금융 교육, 시장 인텔리전스, 안전한 모의 거래 연습을 아프리카에서 만든 하나의 플랫폼에 담았습니다.",learn:"금융시장을 단계별로 배우기",markets:"명확한 데이터 표시로 글로벌 시장 추적",practice:"실제 자본을 위험에 노출하기 전에 모의 거래 연습",risk:"리스크 점검과 학습 도구 활용",cta:"NexAI Global Markets 둘러보기",disclaimer:"교육 및 시뮬레이션 전용입니다. 실제 자금 거래는 활성화되지 않았습니다.",countries:["대한민국"]},
  tr:{code:"tr",label:"Türkçe",headline:"Küresel piyasaları kendi dilinizde anlayın.",subhead:"NexAI finansal eğitim, piyasa zekâsı ve güvenli işlem pratiğini Afrika’da geliştirilen tek platformda birleştirir.",learn:"Finansal piyasaları adım adım öğrenin",markets:"Küresel piyasaları açık veri etiketleriyle takip edin",practice:"Sermayenizi riske atmadan önce kâğıt üzerinde işlem yapın",risk:"Risk kontrollerini ve öğrenme araçlarını kullanın",cta:"NexAI Global Markets’i keşfedin",disclaimer:"Yalnızca eğitim ve simülasyon içindir. Gerçek parayla işlem etkin değildir.",countries:["Türkiye"]},
  sw:{code:"sw",label:"Kiswahili",headline:"Elewa masoko ya dunia kwa lugha yako.",subhead:"NexAI inaunganisha elimu ya fedha, uelewa wa masoko na mazoezi salama ya biashara kwenye jukwaa lililojengwa Afrika.",learn:"Jifunze masoko ya fedha hatua kwa hatua",markets:"Fuatilia masoko ya dunia kwa lebo wazi za data",practice:"Fanya mazoezi ya paper trading kabla ya kuhatarisha mtaji",risk:"Tumia ukaguzi wa hatari na zana za kujifunza",cta:"Gundua NexAI Global Markets",disclaimer:"Kwa elimu na majaribio pekee. Biashara ya fedha halisi haijawashwa.",countries:["Kenya","Tanzania","Uganda"]},
  ha:{code:"ha",label:"Hausa",headline:"Fahimci kasuwannin duniya a harshenka.",subhead:"NexAI ya haɗa ilimin kuɗi, bayanan kasuwa da atisayen ciniki cikin aminci a dandali da aka gina a Afirka.",learn:"Koyi kasuwannin kuɗi mataki-mataki",markets:"Bi kasuwannin duniya tare da bayanan da aka bayyana a sarari",practice:"Yi atisayen paper trading kafin saka jari cikin haɗari",risk:"Yi amfani da binciken haɗari da kayan koyo",cta:"Binciki NexAI Global Markets",disclaimer:"Don ilimi da kwaikwayo kawai. Ba a kunna ciniki da kuɗi na gaske ba.",countries:["Nigeria","Niger","Ghana"]},
  zu:{code:"zu",label:"isiZulu",headline:"Qonda izimakethe zomhlaba ngolimi lwakho.",subhead:"I-NexAI ihlanganisa imfundo yezezimali, ulwazi lwemakethe nokuzijwayeza ukuhweba ngokuphepha epulatifomu eyakhiwe e-Afrika.",learn:"Funda izimakethe zezimali kancane kancane",markets:"Landela izimakethe zomhlaba ngedatha echazwe ngokucacile",practice:"Zijwayeze nge-paper trading ngaphambi kokubeka imali engcupheni",risk:"Sebenzisa ukuhlolwa kobungozi namathuluzi okufunda",cta:"Hlola i-NexAI Global Markets",disclaimer:"Imfundo nokulingisa kuphela. Ukuhweba ngemali yangempela akukavulwa.",countries:["South Africa"]},
  xh:{code:"xh",label:"isiXhosa",headline:"Qonda iimarike zehlabathi ngolwimi lwakho.",subhead:"I-NexAI idibanisa imfundo yezemali, ulwazi lweemarike kunye noqeqesho olukhuselekileyo lokurhweba kwiqonga elakhiwe eAfrika.",learn:"Funda iimarike zemali inyathelo ngenyathelo",markets:"Landela iimarike zehlabathi ngedatha ebhalwe ngokucacileyo",practice:"Ziqhelise nge-paper trading phambi kokubeka imali emngciphekweni",risk:"Sebenzisa uhlolo lomngcipheko nezixhobo zokufunda",cta:"Jonga i-NexAI Global Markets",disclaimer:"Yemfundo nokulinganisa kuphela. Urhwebo ngemali yokwenene alukavulwa.",countries:["South Africa"]},
  af:{code:"af",label:"Afrikaans",headline:"Verstaan wêreldmarkte in jou taal.",subhead:"NexAI bring finansiële opvoeding, markintelligensie en veilige handels-oefening saam op een platform wat in Afrika gebou is.",learn:"Leer finansiële markte stap vir stap",markets:"Volg wêreldmarkte met duidelik gemerkte data",practice:"Oefen met papierhandel voordat jy kapitaal waag",risk:"Gebruik risikokontroles en leerhulpmiddels",cta:"Verken NexAI Global Markets",disclaimer:"Slegs vir opvoeding en simulasie. Handel met regte geld is nie geaktiveer nie.",countries:["South Africa","Namibia"]}
};

export const marketingLocaleCodes = Object.keys(marketingLocales);
